include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: [lib/src/l10n/**]

linter:
  rules:
    # Error rules
    avoid_types_as_parameter_names: true
    hash_and_equals: true
    test_types_in_equals: true
    use_build_context_synchronously: true

    # Style rules
    always_declare_return_types: true
    always_specify_types: true
    await_only_futures: true
    camel_case_types: true
    constant_identifier_names: true
    empty_catches: true
    file_names: true
    library_names: true
    library_prefixes: true
    non_constant_identifier_names: true
    prefer_asserts_with_message: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_function_declarations_over_variables: true
    prefer_if_null_operators: true
    prefer_single_quotes: true
    provide_deprecation_message: true
    unnecessary_late: true
    unnecessary_new: true
    use_full_hex_values_for_flutter_colors: true

    # Pub rules
    package_names: true