name: empathetech_ss_api
description: "Needs a new description"
version: 2.0.0
repository: https://github.com/Empathetech-LLC/empathetech_ss_api

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Flutter (Google)
  cloud_firestore: ^5.4.2
  firebase_auth: ^5.3.0
  
  # Community
  cached_network_image: ^3.4.1
  email_validator: ^3.0.0
  flutter_platform_widgets: ^7.0.1

  empathetech_flutter_ui:
    path: ../empathetech_flutter_ui

dev_dependencies:
  dartdoc: ^8.1.0
  dependency_validator: ^4.1.0
  flutter_lints: ^4.0.0