name: empathetech_ss_api
description: Firebase API code for Empathetech's Smoke Signal
version: 1.0.0
repository: https://github.com/Empathetech-LLC/empathetech_ss_api

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  # Google
  flutter:
    sdk: flutter
  firebase_core: ^2.3.0
  firebase_auth: ^4.1.4
  firebase_messaging: ^14.1.2
  cloud_firestore: ^4.1.0
  cloud_functions: ^4.0.10

  # Community
  empathetech_flutter_ui:
    path: ../empathetech_flutter_ui
  cached_network_image: ^3.2.3
  flutter_platform_widgets: ^3.2.0

dev_dependencies:
  dependency_validator: ^3.0.0
  