name: Run Flutter analyze on code prior to publishing

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Engage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Analyze package
        run: |
          flutter pub get
          flutter analyze